<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_lanjutkan</name>
   <tag></tag>
   <elementGuidId>b3f60162-fd23-4cff-831d-8ca49e6dc428</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lanjutkan > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='lanjutkan']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a5f5f408-c6cc-4837-8292-5090c0d8cc70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lanjutkan</value>
      <webElementGuid>3d93ed6c-f6a7-45f9-99ad-c22e55cdc15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lanjutkan&quot;)/p[1]</value>
      <webElementGuid>61fb3caf-9bbf-46b6-bee3-e4e87aad0147</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='lanjutkan']/p</value>
      <webElementGuid>cf4160ce-9311-4c8c-b393-cee2e307a8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan format email yang benar dan valid.'])[1]/following::p[1]</value>
      <webElementGuid>406bf3fe-4ded-41a4-a905-231f22b32cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar sekarang'])[1]/following::p[2]</value>
      <webElementGuid>b420b24d-6f5f-43fd-8398-b9338419910a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atau'])[1]/preceding::p[1]</value>
      <webElementGuid>4ac739f7-4d4b-4e7f-99ac-63064bcf6959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lanjutkan dengan Google'])[1]/preceding::p[1]</value>
      <webElementGuid>76c1d76b-5c53-4136-87d0-504ce7055d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lanjutkan']/parent::*</value>
      <webElementGuid>3b04e8a6-c336-4d6a-8050-a92b568ef549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/p</value>
      <webElementGuid>0973f83b-4279-42eb-85cd-967788b9a8dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Lanjutkan' or . = 'Lanjutkan')]</value>
      <webElementGuid>0bee91f0-67b8-4911-96d6-5548d091fe20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar sekarang'])[1]/following::p[3]</value>
      <webElementGuid>736cc30c-e84d-412d-bcf9-8a71bb6a03c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum punya akun?'])[1]/following::p[3]</value>
      <webElementGuid>a3d32a7b-9196-48dd-8bc6-62293eafc282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
