<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>076d7558-80a5-493f-bf39-70d0c31013c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9853eee-b8c4-486e-b95a-1c64a5d19818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputField</value>
      <webElementGuid>543abe10-b89f-4d96-905b-45782572cc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inputField</value>
      <webElementGuid>8f540e2c-ff96-4939-bac5-db1e57968418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-default h-10 p-4 w-full focus:outline-none border-grey-30</value>
      <webElementGuid>5a1fd797-66dd-400d-904e-858bb1d834b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputField&quot;)</value>
      <webElementGuid>badbe881-ad35-4f1f-8ee5-7e26b1089df7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputField']</value>
      <webElementGuid>c30df146-e157-4c4f-b9ba-dadd9902d87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>20ef4a24-393e-4c3a-ac38-76eee6bfd1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3c548b5f-f4a2-4c42-b8e1-450ce9889a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputField' and @name = 'inputField']</value>
      <webElementGuid>258bb158-ea09-400b-99b4-1f4d35d1d908</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
