<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_nanti saja</name>
   <tag></tag>
   <elementGuidId>5dc88edd-e2a4-463a-8705-bf202ccf0aa4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#moe-dontallow_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='moe-dontallow_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>68455868-368c-4054-9221-a826b8f827e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>moe-dontallow_button</value>
      <webElementGuid>c4ec2a28-d517-40e4-a1b0-0d269a89f17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-style</name>
      <type>Main</type>
      <value>{'color': webPushPreview['bannerv2']['web']['closeButton']['color'],'background':webPushPreview['bannerv2']['web']['closeButton']['backgroundColor']}</value>
      <webElementGuid>722595e3-99fa-4245-b568-6fc1c07a4796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>3fcf0647-e222-48a8-b30c-260c4b630e6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nanti saja</value>
      <webElementGuid>0ae9a805-9222-4b19-98ca-a0ca3727cb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;moe-dontallow_button&quot;)</value>
      <webElementGuid>cd741065-4317-4a95-8e22-5dddb6f181ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='moe-dontallow_button']</value>
      <webElementGuid>389b6318-3abf-467f-9276-63d3007e7c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='desktopBannerWrapped']/div/div[3]/div/button</value>
      <webElementGuid>823afff4-5951-44da-8dca-db3577ea322a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktifkan notifikasi untuk mendapatkan berita terbaru dari Kompas.id'])[1]/following::button[1]</value>
      <webElementGuid>d44cf5e5-032e-4df5-9253-bc34fe13f67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ya, aktifkan'])[1]/preceding::button[1]</value>
      <webElementGuid>2d6c46f7-5aa8-47ae-a0c1-5fb64ce259e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menu'])[1]/preceding::button[2]</value>
      <webElementGuid>6a3d7649-86f5-4862-bee1-b0a5343ff2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nanti saja']/parent::*</value>
      <webElementGuid>accfe715-aa2f-480f-b1be-9ba2e9b3e0f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>65f8bf95-b0f3-47ab-b965-1b3ea7405dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'moe-dontallow_button' and (text() = 'Nanti saja' or . = 'Nanti saja')]</value>
      <webElementGuid>f8683323-7658-4c8d-aa03-d978e56cc78e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
