<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Menu_login</name>
   <tag></tag>
   <elementGuidId>c06c933b-0a76-4cc0-8c3a-542b6a150baf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div/header/div/div[3]/div/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8b9e5efe-0098-4fac-ab17-583ca4b63d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>40eebaae-9d9e-4356-8b5c-a499ce541cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;relative&quot;]/div[@class=&quot;relative&quot;]/header[@class=&quot;flex flex-col z-40 kui-2M0 kui-2T5 kui-1a9 kui-1r1&quot;]/div[@class=&quot;flex max-w-3xl mx-auto py-2 text-sm w-full&quot;]/div[@class=&quot;flex-1&quot;]/div[@class=&quot;flex h-full items-center justify-end&quot;]/a[@class=&quot;kui-NhM kui-uDJ kui-3W_ kui-2oY kui-2pr&quot;]/span[1]</value>
      <webElementGuid>a5aae814-022d-4f92-9f01-735432ccf903</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div/header/div/div[3]/div/a[2]/span</value>
      <webElementGuid>973b6e1a-f991-4a5e-8d0f-048069d7a750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berlangganan'])[1]/following::span[1]</value>
      <webElementGuid>b8e429f6-9627-4052-9142-1183577447f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari'])[1]/following::span[2]</value>
      <webElementGuid>3613f42d-31db-4479-a3a9-9a3580d5fd3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Topik Hangat'])[1]/preceding::span[1]</value>
      <webElementGuid>54e297bf-c60c-45c4-ba9c-21c2d613545e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='satu abad nu'])[1]/preceding::span[1]</value>
      <webElementGuid>57d58dcf-c7f0-4571-a0fa-e15b73c20bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masuk']/parent::*</value>
      <webElementGuid>8ce40036-fac3-4e14-8e1a-5470fa23412f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>fe736314-13ac-4672-8195-383c434ff49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>3b6437be-d7fc-4f3b-99bb-a007dc10afeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile App'])[1]/preceding::span[1]</value>
      <webElementGuid>159af774-f35f-41d7-ac2a-ff370154463a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gerai'])[1]/preceding::span[2]</value>
      <webElementGuid>668ac294-a39a-4c89-b71d-1e77eb9926ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
